version: '2.2'
services:
  # serverless.io is used to deploy your serverless functions.
  # Learn more at https://serverless.io.
  # The URL for all serverless functions will include 'v1' in the path.
  # To change this, substitute all references to 'v1' to the top-level path that you
  # would like to use.
  serverless:
    build:
      dockerfile: serverless.Dockerfile
      context: .
    env_file: .env
    environment:
      SERVERLESS_ENVIRONMENT: "production"
    volumes:
      - $PWD:/app
    working_dir: /app
    entrypoint:
      - serverless
      - --stage
      - v1
  # Terraform is used to provision infrastructure required by Serverless
  # to host your application.
  # Learn more at https://terraform.io.
  terraform:
    build:
      dockerfile: terraform.Dockerfile
      context: .
    env_file: .env
    environment:
      TERRAFORM_STATE_S3_KEY: ${TERRAFORM_STATE_S3_KEY}
      TF_VAR_environment: "production"
      TF_VAR_domain_tld: ${DOMAIN_TLD}
      TF_VAR_domain_path:  ${DOMAIN_PATH}
    volumes:
      - $PWD:/app
    working_dir: /app
  # validate-serverless-infra ensures that the serverless infrastructure to be
  # created by Terraform is valid.
  # Ensure that Terraform is configured appropriately in your .env.
  validate-serverless-infra:
    extends: terraform
    command:
      - plan
      - --input=false
  # deploy-serverless-infra provisions your serverless infrastructure.
  # Ensure that Terraform is configured appropriately in your .env.
  deploy-serverless-infra:
    extends: terraform
    command:
      - apply
      - --auto-approve=true
      - --input=false
  # destroy-serverless-infra destroys serveless infrastructure.
  destroy-serverless-infra:
    extends: terraform
    command:
      - destroy
      - -force
      - --input=false
  # deploy-serverless-function deploys your serverless functions into a production
  # environment. The URL for all serverless functions will include 'v1' in the path.
  # To change this, substitute all references to 'v1' to the top-level path that you
  # would like to use.
  deploy-serverless-functions:
    extends: serverless
    command:
      - deploy
  # serverless-starter assumes that you want to host your functions at a custom
  # domain in production only. deploy-serverless-domain configures this.
  # See serverless.yml if you'd like to turn this off.
  deploy-serverless-domain:
    extends: serverless
    command:
      - create_domain

  # destroy-serverless-functions removes serverless functions from your production
  # environment.
  destroy-serverless-functions:
    extends: serverless
    command:
      - remove
